### ISSUE TITLE
Can we add our own Corner images?

### ISSUE THREAD

**Issue by YazzyTales** [kozakdenys/qr-code-styling#108]
Is is possible to add our own corner styles?
Even if I have to edit the code on my own just need to know where the corner style is being created
Something similar to QRCode Monkey

**Comment by danielaloycedaniel** [comment]
I think the best way is to enclose a qr code inside a parent div then use that div for external styling such as border radius as so on.

**Comment by kozakdenys** [comment]
@YazzyTales  There is no easy way to customize corners. You can clone this repo and modify this file to make your own styles https://github.com/kozakdenys/qr-code-styling/blob/master/src/figures/cornerSquare/QRCornerSquare.ts
I will add more styles in the future, but we have a limited set of them for now.
