### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Celibioux** [kozakdenys/qr-code-styling#114]
Hello just to say it's a great package ^^
it still maintained ? 

Thanks in advance

**Comment by Celibioux** [comment]
i'm really sorry bro i didn't know that you are from ukraine so it was so rude from me to ask something in those times 

i wish you all safe your family and beloved ones ! we are all with you with our hearts from all around the world

**Comment by kozakdenys** [comment]
@Celibioux thank you!
Currently, I am making all efforts to help my family, friends, and country to survive.
I hope this war will finish soon and I will be able to come back to my regular life and continue to work on software.
Thank you for understanding!

**Comment by Celibioux** [comment]
@kozakdenys of course bro i understand and i hope all the best for you , your family and friends 
we all are sad for this war and we wish it ends soon 
be safe bro

**Comment by kozakdenys** [comment]
@Celibioux I am already back, so I am closing this issue ❤️
