### ISSUE TITLE
One page solution

### ISSUE THREAD

**Issue by stefanocutelle** [kozakdenys/qr-code-styling#117]
Hi mate @kozakdenys good job! 
I wanted to know if you had set up an html page like https://qr-code-styling.com/ with the functions of https://unpkg.com/ so that you could load the page on a shared hosting or on a local machine without installing node ... can you help me if you haven't?

**Comment by kozakdenys** [comment]
Hi @stefanocutelle sorry for the late response. I am closing it, if it is still relevant, please reopen.
