### ISSUE TITLE
Downloaded images in Vue 3 not working

### ISSUE THREAD

**Issue by JosephShepin** [kozakdenys/qr-code-styling#121]
I built a QR code application with Vue2, and I recently ported it over into Vue3, however there is a problem with the conversion to png, jpeg, svg. The generated image strings are not valid because putting them into a   base64 -> png utility yields an invalid result. 
![image](https://user-images.githubusercontent.com/31457361/164987174-ef10d508-1988-4e4f-a402-e17ba7a644ee.png)
![image](https://user-images.githubusercontent.com/31457361/164987183-27cd82c9-dd07-4961-886b-3a19dee4a6a6.png)

**Comment by kozakdenys** [comment]
@JosephShepin please check the vue example https://github.com/kozakdenys/qr-code-styling-examples/tree/master/examples/vue
