### ISSUE TITLE
QR Code is empty

### ISSUE THREAD

**Issue by MRCaptain-Vijay** [kozakdenys/qr-code-styling#123]
Hi,
     I am getting a client error in my console while trying to display the QR code. How to fix this issue ?
![image](https://user-images.githubusercontent.com/84058637/165452710-1b3c1641-44cf-469c-9003-c0312117f473.png)
![image](https://user-images.githubusercontent.com/84058637/165452770-75d25bbf-9b3c-4db1-acad-7503a2204f54.png)

**Comment by kozakdenys** [comment]
@MRCaptain-Vijay please try latest version of library and reopen issue, if it is still relevant
