### ISSUE TITLE
Download Method

### ISSUE THREAD

**Issue by GabrielDuarteMG** [kozakdenys/qr-code-styling#13]
Hello, 

I wanna download my qr but, on call download method, this image comeback blank. 

Example:

![qr](https://user-images.githubusercontent.com/25777813/70741054-48adb700-1cf9-11ea-9b6a-a851944eb875.png)

**Comment by wilderbonsai** [comment]
Heya, I was having this issue. I was able to fix it by adding a timeout before downloading 
```qrCode.append(document.getElementById("canvas"));
        setTimeout(() => {qrCode.download()}, 1000)```

If I did it right away, it would not give the canvas enough time to place the image.

**Comment by GabrielDuarteMG** [comment]
That's problem not solve, 
So i fixed using anonymous crossOrigin to generate image . like this

```
      const dotSize = Math.floor(minSize / count);
      const xBeginning = Math.floor((options.width - count * dotSize) / 2);
      const yBeginning = Math.floor((options.height - count * dotSize) / 2);
      const image = new Image();
      image.crossOrigin = 'anonymous'

```
On File QRCanvas.ts - Line 134

**Comment by ScottDurkin** [comment]
> That's problem not solve,
> So i fixed using anonymous crossOrigin to generate image . like this
> 
> ```
>       const dotSize = Math.floor(minSize / count);
>       const xBeginning = Math.floor((options.width - count * dotSize) / 2);
>       const yBeginning = Math.floor((options.height - count * dotSize) / 2);
>       const image = new Image();
>       image.crossOrigin = 'anonymous'
> ```
> 
> On File QRCanvas.ts - Line 134

Hey, I’m unable to edit the source files. Do you think you could send me this js file or hop on discord to show me how to setup?

Much appreciated either way!

**Comment by kozakdenys** [comment]
Hi @GabrielDuarteMG and @wilderbonsai 
I updated the version of the package, now you show have a chance to call download method immediately. (it will download the QR code once it get the image form the source)

**Comment by kozakdenys** [comment]
@wilderbonsai and for your case I added the possibility to change crossOrigin value of the image. Now you need to pass `options.imageOptions.crossOrigin === 'anonymous'` value.
