### ISSUE TITLE
Increase quality with png jpg webp format 

### ISSUE THREAD

**Issue by chiptu** [kozakdenys/qr-code-styling#134]
Hey Everyone,

I'm having a pixelisation problem with my qrcode when i add a logo or change format to dot .

![example](https://user-images.githubusercontent.com/35498845/180034853-ba7d1541-e843-43cf-9f3b-6ecc55bfee7c.png)

I have changed the width, height , error correction level but i think it is how the qrcode is generated inside the lib.

Do anyone encoutered this problem and know how to increase the quality ?

**Comment by sebastienb** [comment]
@chiptu, how did you resolve this?
