### ISSUE TITLE
CORS Origin Issue for AWS Cloudfront Image Link

### ISSUE THREAD

**Issue by FAME360** [kozakdenys/qr-code-styling#145]
Getting Access to the CORS error for an Image. But, that image is being opened up when trying to load directly through the URL. Please have a look.

'https://d33qrt5d6zzez8.cloudfront.net/uploads/profile_image/165944772577_profile_image.png' from origin 'https://member.voxiproducts.com/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

![image](https://user-images.githubusercontent.com/34950506/186754180-5b404a7f-6e90-4001-b93d-6c49e7464cd5.png)

@kozakdenys / @justraman Please check this (#120) as well. Several more people are facing the same. Please check it.

**Comment by pedrojobs13** [comment]
You're using a different origin, so you need change your crossOrigin in imageOptions if you to use ` imageOptions: {
      crossOrigin: "https://d33qrt5d6zzez8.cloudfront.net/",
      margin: 10,
    },` that will work
