### ISSUE TITLE
Is it available in NodeJS?

### ISSUE THREAD

**Issue by sunny-2504** [kozakdenys/qr-code-styling#147]
I'm trying to create an API in NodeJS. I need an example of how to use it in NodeJS

**Comment by buza-me** [comment]
@sunny-2504 did you try to use it in Node? I bet you did.
Did you see the error saying "document.createElement is not defined"? I bet you did :)
So is it available in Node?

**Comment by buza-me** [comment]
Sorry for being a bit salty but it is a bit funny :)

**Comment by sunny-2504** [comment]
Yes, it is available in NodeJS. You are so dumb that you can't even understand my question. You thought that I would really use document.CreateElement in NodeJS? I bet you did! FYI it is available in NodeJS

**Comment by buza-me** [comment]
@sunny-2504 haha, don't be mad mate! The library uses document.createElement internally, so you can't use it in Node xD
