### ISSUE TITLE
I can't create more than one qr code

### ISSUE THREAD

**Issue by Roderen** [kozakdenys/qr-code-styling#165]
I'm trying to create two different qr codes, but for some reason I can't do it. The second qr code is created, but it turns out crooked (see screenshot). If I delete the first qr code, the second one works.
[Screenshot](https://imgur.com/a/4yFEVvR)

`function genQRVcard() {
    let wrapqr = document.querySelector(".agent__qr-generate"),
        qr = document.querySelector(".agent__qr svg");
    if (!qr) {
        const qrCode = new QRCodeStyling({
            width: '160',
            height: '160',
            type: "svg",
            data: window.location.href + 'vcard/',
            image: "/public/icons/penthouse/qr-penthouse-icon.svg",
            dotsOptions: { color: "#333333", type: "extra-rounded" },
            backgroundOptions: { color: "#ffffff", },
            imageOptions: { crossOrigin: "anonymous", margin: 5 }
        });
        qrCode.append(wrapqr);
    }
    return false;
}`

`function modarQR() {
    let wrapper = document.querySelector(".modal__qr-generate"),
        qrSvg = document.querySelector(".modal__qr svg");
    if (!qrSvg) {
        const qrCodeModar = new QRCodeStyling({
            width: '230',
            height: '230',
            type: "svg",
            data: window.location.href,
            image: "/public/icons/penthouse/qr-penthouse-icon.svg",
            dotsOptions: { color: "#333333", type: "extra-rounded" },
            backgroundOptions: { color: "transparent", },
            imageOptions: { crossOrigin: "anonymous", margin: 5 }
        });
        qrCodeModar.append(wrapper);
    }
    return false;
}`

**Comment by niveditasancheti11** [comment]
Yes. It generates onyl 1 qr code.

**Comment by MoralGray** [comment]
https://codesandbox.io/s/tender-resonance-wh2mms?file=/index.html

Version 1.5.0 has a bug.

If we want to generate more than one qr code on the same page, we will get an error.
The second qr code has an broken layout.
![image](https://user-images.githubusercontent.com/68497585/215787643-d791cd7c-d7ce-42f2-97af-986b95b95070.png)

1. If we change the version to 1.3.0, then the error will disappear.
2. Or we can change type: "svg" to type: "canvas"

Both options can fix the error.
![image](https://user-images.githubusercontent.com/68497585/215788475-9e40ec92-ac04-4096-8b27-4c3a5eb5f560.png)

**Comment by kozakdenys** [comment]
This issue was fixed in the version [v1.7.1](https://github.com/kozakdenys/qr-code-styling/releases/tag/v1.7.1) and above
