### ISSUE TITLE
Download to SVG

### ISSUE THREAD

**Issue by F2BEAR** [kozakdenys/qr-code-styling#17]
Hi Denys, I wanted to know if it will be possible on a near future to add svg as one of the download file extensions.

I see it really useful to me because for a couple of projects I need to embed svg Qr codes on my pages, and I think that I'm not the only one with the same need.

This is just a recommendation, there is no need or hurry to add it! I love this project and I want to see how it grows.

**Comment by seraguirre** [comment]
Any progress on this subject?

**Comment by kozakdenys** [comment]
SVG support added to the [1.4.0](https://github.com/kozakdenys/qr-code-styling/releases/tag/v1.4.0) version.
