### ISSUE TITLE
Generating more than 1 QR Code in 1.5 replaces the earlier generated codes

### ISSUE THREAD

**Issue by petersephrin** [kozakdenys/qr-code-styling#171]
I was trying to generate more than one QR code on the same page for different elements. On 1.5 this ends up replacing the previos codes so you end up with the same qr code in the end. 

FIX
I had to downgrade to 1.3 maybe 1.4 also would fix that.

Please review and fix the bug, thank you

**Comment by eddiemcconkie** [comment]
I'm having this same issue on 1.6.0-rc.1
If I generate multiple codes using canvas then it works correctly, but generating multiple codes with svg results in the same image.
Downgrading did not resolve the issue in this case.

**Comment by kozakdenys** [comment]
Hi @petersephrin @eddiemcconkie the issue with 2 qr-codes on the same page was fixed in version [v1.7.1](https://github.com/kozakdenys/qr-code-styling/releases/tag/v1.7.1) and above.
Sorry for missing for so long 🥲
