### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by natainditama** [kozakdenys/qr-code-styling#176]

**Comment by BuyMyBeard** [comment]
I have exactly the same problem! When will they fix it?

**Comment by BuyMyBeard** [comment]
I have the exact same problem! When will they fix it?

**Comment by kozakdenys** [comment]
@natainditama @BuyMyBeard sorry for missing for so long 🥹

It was introduced in version [v1.6.0](https://github.com/kozakdenys/qr-code-styling/releases/tag/v1.6.0) and above 🎉
