### ISSUE TITLE
scanner

### ISSUE THREAD

**Issue by davydavydavy05** [kozakdenys/qr-code-styling#181]
best library to scan this?

**Comment by Jcoloma13** [comment]
Someone find some library for react that works well ?

**Comment by kozakdenys** [comment]
Hi @davydavydavy05, any scanner should be able to scan it. I will close this issue as it is not a scope of this package. It is better to ask on stackoverflow.com

**Comment by kozakdenys** [comment]
@Jcoloma13 you can use this library with React. Here is [example](https://codesandbox.io/p/sandbox/qr-code-styling-react-example-l8rwl?file=%2Fpackage.json)
