### ISSUE TITLE
error

### ISSUE THREAD

**Issue by djshox** [kozakdenys/qr-code-styling#182]

**Comment by djshox** [comment]
<template>
  <div>
    <VueQr3
          :width="1200"
          :height="1200"
          data="tokencode"
          :qrOptions="{
            typeNumber: 0,
            mode: 'Byte',
            errorCorrectionLevel: 'H',
          }"
          :imageOptions="{
            hideBackgroundDots: true,
            imageSize: 0.42,
            margin: 30,
          }"
          :dotsOptions="{
            type: 'dots',
            color: '#000000',
            gradient: {
              type: 'linear',
              rotation: 0,
              colorStops: [
                { offset: 0, color: '#000000' },
                { offset: 1, color: '#000000' },
              ],
            },
          }"
          :backgroundOptions="{ color: '#ffffff' }"
          :cornersSquareOptions="{ type: 'dot', color: '#000000' }"
          :cornersDotOptions="{ type: undefined, color: '#000000' }"
          fileExt="png"
          :download="false"
          myclass=" text-center"
          imgclass="img-qr-i"
          downloadButton="my-button"
          :downloadOptions="{ name: 'vqr', extension: 'png' }"
        ></VueQr3></div>
</template>

<script lang="ts">
import {
  defineComponent,
  onBeforeUnmount,
  defineAsyncComponent
} from 'vue'

export default defineComponent({
  name: 'VueQr3',
  components: {
    VueQr3: defineAsyncComponent(() =>
      Promise.resolve(import('vue3-qr-code-styling'))
    ),
  },
  setup () {
    return {
    }
  }
})
</script>

**Comment by kozakdenys** [comment]
It sounds sad 🥲
