### ISSUE TITLE
Downloaded SVG turns to blacksquare when opened with Illustrator and other editors

### ISSUE THREAD

**Issue by Glorfi** [kozakdenys/qr-code-styling#188]
Hi there! Thanks for the awsome library. Yet there's an issue with downloaded SVG file. 
Once I download an SVG file and try to open it with something other than a browser or Figma, it turns into a black square when I import it for instance in Adobe Illustrator or Photoshop. Any ideas on how to solve it? 

Bellow is sample SVG generated with the library.
![sample_generated_qr_svg](https://github.com/kozakdenys/qr-code-styling/assets/119957768/ac76d0aa-80c4-460f-b1ef-6dcda30cda10)

<details>
  <summary>The options used to make one:</summary>

> const getOptions = () => {
>     return {
>       width: 200,
>       height: 200,
>       type: 'canvas' as DrawType,
>       data: props.url,
>       image: `data:image/svg+xml;base64,${btoa(getLogo(''))}`,
>       margin: 0,
>       qrOptions: {
>         typeNumber: 0 as TypeNumber,
>         mode: 'Byte' as Mode,
>         errorCorrectionLevel: 'H' as ErrorCorrectionLevel,
>       },
>       imageOptions: {
>         hideBackgroundDots: true,
>         imageSize: 0.4,
>         margin: 20,
>         crossOrigin: 'anonymous',
>       },
>       dotsOptions: {
>         color: qrColor,
>         type: 'rounded' as DotType,
>       },
>       backgroundOptions: {
>         color: '#FFFFFF',
>       },
>       cornersSquareOptions: {
>         color: qrColor,
>         type: '' as CornerSquareType,
>       },
>       cornersDotOptions: {
>         color: qrColor,
>         type: '' as CornerDotType,
>       },
>     } as Options;
>   };

</details>

  
   Any ideas on how to solve it?

**Comment by waglons** [comment]
Try opening the file in Illustrator with a "File > Open" instead of dragging it in.  We noticed that solved this issue.

**Comment by sebastienb** [comment]
having the same issue in sketch.
![CleanShot 2024-06-04 at 10 18 38@2x](https://github.com/kozakdenys/qr-code-styling/assets/2538981/52541b9e-9b61-47cf-b456-4381f518f3f1)

**Comment by kozakdenys** [comment]
Hi @Glorfi, @waglons , @sebastienb 
It should be partially fixed in version [v1.8.0](https://github.com/kozakdenys/qr-code-styling/releases/tag/v1.8.0).
The image is still not displayed in Illustrator, but I can't fix it as Illustrator doesn't fully support SVG standard

**Comment by makingtheimpact** [comment]
I'm having this black square problem in v1.8.4. I've been trying to get it to work and create a workaround for several days, but haven't had any luck. Is there a solution for it yet?
