### ISSUE TITLE
QR DOWNLOADING FAILS IN REACT

### ISSUE THREAD

**Issue by veldfolds** [kozakdenys/qr-code-styling#191]
I have tried the react sample in the sandbox and the same code in my dev environment and yet  when i click the download button the qr code doesn't download

**Comment by kozakdenys** [comment]
Hi @veldfolds
I can't reproduce this issue. I can download QR from [codesandbox](https://codesandbox.io/s/qr-code-styling-react-example-l8rwl?file=/src/App.js).
Maybe you have browser configs that block download.
If this issue still relevant, please reopen it with more details
