### ISSUE TITLE
Multi QR Code Generation Error

### ISSUE THREAD

**Issue by PNB007** [kozakdenys/qr-code-styling#194]
Here is my code 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>QR Code Styling</title>
    
    <script type="text/javascript" src="https://unpkg.com/qr-code-styling@1.5.0/lib/qr-code-styling.js"></script>
</head>
<body>
	<div id="qr_content"></div>
	<script type="text/javascript">
		function generateQrCode(ctrlId, qrText) {
			qrCode = new QRCodeStyling({
				width: 300,
				height: 300,
				type: "svg",
				data: qrText,
				margin:0,
				image: "https://upload.wikimedia.org/wikipedia/commons/5/51/Facebook_f_logo_%282019%29.svg",
				qrOptions:{typeNumber:"0",mode:"Byte",errorCorrectionLevel:"Q"},
				
				dotsOptions: {
					color: "#000000",		// Black
					type: "dots"
				},
				cornersSquareOptions:{
					type:"extra-rounded",
					color:"#000080"
				},
				cornersSquareOptionsHelper:{
					colorType:{
						single:true,
						gradient:false
					},
					gradient:{
						linear:true,
						radial:false,
						color1:"#000000",
						color2:"#000000",
						rotation:"0"
					}
				},
				cornersDotOptions: {
					color: "#000080",		// Navy Blue
					type: "dots"
				},
				cornersDotOptionsHelper:{
					colorType:{
						single:true,
						gradient:false
					},
					gradient:{
						linear:true,
						radial:false,
						color1:"#000000",
						color2:"#000000",
						rotation:"0"
					}
				}
			});
			qrCode.clear;
			qrCode.append(document.getElementById(ctrlId));
		}
		var html = "";
		for (let i = 1; i < 10; i++) {
			html += '<div id="canvas'+i+'"></div><br>';
		}
		var xx = document.getElementById("qr_content");
		xx.innerHTML = html;
		
		var odd = "pushpenbanerjee@yahoo.com\n720, Bijay Ch. Das Road\nSainpala, Basirhat-743411\nNorth 24 Parganas, WB, India";
		var even = "pushpenbanerjee@gmail.com\nPanitor, Itinda1\nNorth 24 Parganas, Mobile:8609312084";
		for (let i = 1; i < 10; i++) {
			var yy = document.getElementById('"canvas"'+i+'"');
			if(i%2 == 0){
				qrText = even;
			}else{
				qrText = odd;
			}
			generateQrCode("canvas"+i, qrText);
		}
	</script>
</body>
</html>

![qr_code_styling](https://github.com/kozakdenys/qr-code-styling/assets/47871713/b61037bd-2c3a-4aa5-b7db-1b9979bca481)

Only odd row QR Code are shown correctly but even row QR Code not shown properly. Please Solve it.
Thank  You.

**Comment by kozakdenys** [comment]
Hi @PNB007 , sorry for missing for so long 🥹 
The issue with 2 qr-codes on the same page was fixed in version [v1.7.1](https://github.com/kozakdenys/qr-code-styling/releases/tag/v1.7.1) and above 🎉
