### ISSUE TITLE
How can I donate to this lad?

### ISSUE THREAD

**Issue by YO-SC** [kozakdenys/qr-code-styling#195]
Seriously, great job man. You deserve it.

**Comment by kozakdenys** [comment]
Hi @YO-SC thank you ❤️
I have created [opencollective](https://opencollective.com/qr-code-styling) but it is still under review.
Also, I have created [paid plugin](https://www.npmjs.com/package/qr-border-plugin). If you want to have additional features and support this project I would be super happy 😍
