### ISSUE TITLE
Node support?

### ISSUE THREAD

**Issue by markpiller** [kozakdenys/qr-code-styling#197]
Hi Denys,

Have you thought about expanding the library to include support for node? It would be fantastic if the library would offer all the same capabilities as it does now, but in the server-side environment.

Regards,
Mark

**Comment by kozakdenys** [comment]
@markpiller @trymeouteh sorry for missing for so long 🥹

It was introduced in version [v1.6.0](https://github.com/kozakdenys/qr-code-styling/releases/tag/v1.6.0) and above 🎉
