### ISSUE TITLE
dynamic data value not working

### ISSUE THREAD

**Issue by enchi987** [kozakdenys/qr-code-styling#199]
I am using vuejs version 3, the component value not working when i pass the varialbe instead of plain text

```
<script>
export default {
     props:{
         qrdata: String
   }
}
</script>
<template>
<QRCodeVue3 value={{qrdata}} />
</template>
```

it generated  {{qrdata}} as value

**Comment by Hydronio** [comment]
hey, same issue here, i haven't found a solution

**Comment by liamcharmer** [comment]
Any idea how to solve this?

**Comment by kozakdenys** [comment]
Hi @enchi987 @Hydronio @liamcharmer

I guess, you are using [qrcode-vue3](https://www.npmjs.com/package/qrcode-vue3) but not current package [qr-code-styling](https://www.npmjs.com/package/qr-code-styling). `qrcode-vue3` was created in base of this package, but I am not supporting it. You would better open an issue [here](https://github.com/scholtz/qrcode-vue3/issues).

Also, you can use `qr-code-styling` in Vue too, here is [example](https://github.com/kozakdenys/qr-code-styling-examples/blob/master/examples/vue/src/components/QRCodeStyling.vue)
