### ISSUE TITLE
Error qrcode image genrate  by QR Code Error Correction

### ISSUE THREAD

**Issue by hautv** [kozakdenys/qr-code-styling#201]
I used qr-code-styling to create qrcode, according to the [QR Code Error Correction](https://www.qrcode-tiger.com/en/qr-code-error-correction
) by level M, the above styling was created incorrectly according to the description of the version as shown in the photo!
![styling](https://github.com/kozakdenys/qr-code-styling/assets/13358561/03815e16-e69d-4263-af37-e97f033e2494)
vs image ngx-qrcode
![QR Code Generator](https://github.com/kozakdenys/qr-code-styling/assets/13358561/17a1e7e1-a097-4804-ad3b-3c104fc9b5c2)
How to fix?

**Comment by kozakdenys** [comment]
Hi @hautv
It was fixed in version [v1.7.1](https://github.com/kozakdenys/qr-code-styling/releases/tag/v1.7.1)
Also https://qr-code-styling.com/ has updated version
