### ISSUE TITLE
Multiple svgs show same QRCode

### ISSUE THREAD

**Issue by Psycarlo** [kozakdenys/qr-code-styling#210]
Reproduce steps:

1. Add multiple qrcodes in one page.
2. They should be of type "svg"

Every QRCode will look the same.

**Comment by Psycarlo** [comment]
Clip-path uses the same url id when multiple svgs are present.

**Comment by Psycarlo** [comment]
As per: https://stackoverflow.com/questions/15911717/clippath-in-multiple-svg-tags
We should allow the user to pass an id or this be automatically generated so multiple qrcodes on the same page are correctly rendered.

**Comment by broekema41** [comment]
Just confirming here that in the browser when there are multiple qr codes on a page the page the content the same code. This is only for the svg implementation the canvas one does not have this issue.

**Comment by Nayanchandrakar** [comment]
i am using this package in my project is there way currently to add it

**Comment by kozakdenys** [comment]
Hi @Psycarlo @broekema41 @Nayanchandrakar. This issue should be fixed in version [v1.7.1](https://github.com/kozakdenys/qr-code-styling/releases/tag/v1.7.1) and above.
Please reopen the issue if something doesn't work for you.
