### ISSUE TITLE
How can we add logo(image) with file upload instead of supplying url

### ISSUE THREAD

**Issue by samerlol** [kozakdenys/qr-code-styling#213]
I want to add image to the QR without sending URL, like use buffer or base64

**Comment by mrfrase3** [comment]
You can use the browser's native functionality here: `file.createObjectURL()`

https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL_static

**Comment by samerlol** [comment]
I will try it.

**Comment by samerlol** [comment]
Thanks it works,

I used 
`URL.createObjectURL(image)` where image is a file
