### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by MilanovaSmile** [kozakdenys/qr-code-styling#217]
Last release over three years ago. Pull requests are not accepted. Bugs are not fixed. Is the project dead?

**Comment by barstars** [comment]
No, the project is working. It was changed two months ago README.md.

**Comment by MilanovaSmile** [comment]
<img width="1347" alt="Снимок экрана 2024-09-23 в 13 50 41" src="https://github.com/user-attachments/assets/0954524d-63bb-4411-9915-7e0e9f1ab64a">

The last commit to master was 3 years ago. And a commit that adds one line to the readme doesn't really look like the project is alive.

**Comment by MilanovaSmile** [comment]
What am I getting at? There is a problem (https://github.com/kozakdenys/qr-code-styling/issues/160#issue-1505840156), it is still not solved. I did not look, maybe there is even a pull request...

**Comment by MilanovaSmile** [comment]
@kozakdenys If you are no longer interested in the project, maybe you can appoint people responsible to support it?

**Comment by Psycarlo** [comment]
@MilanovaSmile maybe we should fork it and create a new version of it. This seems dead.

**Comment by kozakdenys** [comment]
Hi @MilanovaSmile @Psycarlo , this project is not dead, I will merge critical PS soon, and going to work on new features too. Sorry for my missing, I didn't have time to work on this project but now I am available
