### ISSUE TITLE
Basic user manual?

### ISSUE THREAD

**Issue by RiverMersey** [kozakdenys/qr-code-styling#24]
Looks like a great project - used by someone that I know!

However, as a complete noob, I don't know how to download it and install it onto a CentOS system.

Once it is there, I wouldn't know how to use it!

Could there be a very basis set of instructions written for this, please?

**Comment by RiverMersey** [comment]
Continue to try to use this project. However, this is as far as I can get...

[root@kayak qr-code-styling]# npm install qr-code-styling
npm ERR! Linux 3.10.0-1127.10.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "qr-code-styling"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install qr-code-styling as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/cjc/qr-code-styling/npm-debug.log


[root@kayak qr-code-styling]# cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', 'qr-code-styling' ]
2 info using npm@3.10.10
3 info using node@v6.17.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData qr-code-styling
8 silly fetchNamedPackageData qr-code-styling
9 silly mapToRegistry name qr-code-styling
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'qr-code-styling',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'qr-code-styling',
12 silly mapToRegistry   name: 'qr-code-styling',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/qr-code-styling
14 verbose request uri https://registry.npmjs.org/qr-code-styling
15 verbose request no auth needed
16 info attempt registry request try #1 at 12:09:20 AM
17 verbose request id 524646923062c836
18 verbose etag W/"390469db94377e47b2deee7b0991d401"
19 verbose lastModified Fri, 21 Aug 2020 13:08:43 GMT
20 http request GET https://registry.npmjs.org/qr-code-styling
21 http 304 https://registry.npmjs.org/qr-code-styling
22 verbose headers { date: 'Sun, 15 Nov 2020 00:09:21 GMT',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'set-cookie': [ '__cfduid=d2ca67e432960b6dac52eade2ffd5cd791605398961; expires=Tue, 15-Dec-20 00:09:21 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
22 verbose headers   'cf-ray': '5f24be33db310085-LHR',
22 verbose headers   'cache-control': 'public, max-age=300',
22 verbose headers   etag: '"390469db94377e47b2deee7b0991d401"',
22 verbose headers   'last-modified': 'Fri, 21 Aug 2020 13:08:43 GMT',
22 verbose headers   vary: 'Accept-Encoding',
22 verbose headers   'cf-cache-status': 'MISS',
22 verbose headers   'cf-request-id': '066ad5346a00000085ad2e8000000001',
22 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
22 verbose headers   server: 'cloudflare' }
23 silly get cb [ 304,
23 silly get   { date: 'Sun, 15 Nov 2020 00:09:21 GMT',
23 silly get     connection: 'keep-alive',
23 silly get     'set-cookie': [ '__cfduid=d2ca67e432960b6dac52eade2ffd5cd791605398961; expires=Tue, 15-Dec-20 00:09:21 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
23 silly get     'cf-ray': '5f24be33db310085-LHR',
23 silly get     'cache-control': 'public, max-age=300',
23 silly get     etag: '"390469db94377e47b2deee7b0991d401"',
23 silly get     'last-modified': 'Fri, 21 Aug 2020 13:08:43 GMT',
23 silly get     vary: 'Accept-Encoding',
23 silly get     'cf-cache-status': 'MISS',
23 silly get     'cf-request-id': '066ad5346a00000085ad2e8000000001',
23 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
23 silly get     server: 'cloudflare' } ]
24 verbose etag https://registry.npmjs.org/qr-code-styling from cache
25 verbose get saving qr-code-styling to /root/.npm/registry.npmjs.org/qr-code-styling/.cache.json
26 verbose correctMkdir /root/.npm correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly rollbackFailedOptional Starting
40 silly rollbackFailedOptional Finishing
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install qr-code-styling as a dependency of itself
43 verbose stack     at checkSelf (/usr/lib/node_modules/npm/lib/install/validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/slide/lib/bind-actor.js:15:8)
43 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules.bundled/slide/lib/chain.js:15:14)
43 verbose stack     at chain (/usr/lib/node_modules/npm/node_modules.bundled/slide/lib/chain.js:20:5)
43 verbose stack     at /usr/lib/node_modules/npm/lib/install/validate-args.js:16:5
43 verbose stack     at /usr/lib/node_modules/npm/node_modules.bundled/slide/lib/async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at /usr/lib/node_modules/npm/node_modules.bundled/slide/lib/async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (/usr/lib/node_modules/npm/node_modules.bundled/slide/lib/async-map.js:51:8)
44 verbose cwd /root/cjc/qr-code-styling
45 error Linux 3.10.0-1127.10.1.el7.x86_64
46 error argv "/usr/bin/node" "/usr/bin/npm" "install" "qr-code-styling"
47 error node v6.17.1
48 error npm  v3.10.10
49 error code ENOSELF
50 error Refusing to install qr-code-styling as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

**Comment by kozakdenys** [comment]
Hi @RiverMersey you are trying to install `qr-code-styling` inside of `qr-code-styling` repository. It throws an error as a circular dependency.
This library is npm module that can be used in the browsers only.
To use it you need to create HTML file (`index.html` for example)  with content similar to this https://github.com/kozakdenys/qr-code-styling#ussage. Then you can open this file via your browser and you will get a generated QR code.

**Comment by kozakdenys** [comment]
Hey, @RiverMersey I found a Medium article about how to use this library.
Thanks, @F2BEAR for the article!

**Comment by F2BEAR** [comment]
Thanks to you for making this library! @RiverMersey if you have any doubts about how it works don't hesitate and ask me
