### ISSUE TITLE
Dots texture smear

### ISSUE THREAD

**Issue by UPS7868** [kozakdenys/qr-code-styling#244]
![image](https://github.com/user-attachments/assets/8609a336-83ef-4096-b1c1-8584d1dbab58)

When generating a QR code using the **"Dots" pixel style**, the points of color render with **long horizontal streaks** and smears. This does not appear to be intentional.

The issue appears to be purely cosmetic as it does not currently affect the ability to scan the QR code [when using black dots on white background; other combinations untested].

**Comment by kozakdenys** [comment]
Hi @UPS7868, It looks strange, never seen it before 😲
Could you please provide more details:

- qr-code-styling version
- full options object
- the browser/ node version

**Comment by UPS7868** [comment]
![image](https://github.com/user-attachments/assets/9eee828b-1da3-4ce5-b012-71e2df7d6df7)

@kozakdenys The styling version of the body pixels are dots. I've gotten the same visual glitch regardless of corner style, corner dot style, color vs gradient, gradient direction, and so on. I'm running the site on Google Chrome. Here is an example of the starter sample with the only change being the texture changing to Dots.

**Comment by kozakdenys** [comment]
@UPS7868, thank you
I will try to investigate

**Comment by UPS7868** [comment]
And thank you for making that website! It's extremely useful and user friendly :)

If I'm able to make a suggestion for future features, it would be for the ability to shift where the gradient partition falls. Some colors overpower others and require the weaker color to have more space to be visible. If it's a huge undertaking, don't feel obligated to add it. It's an extraordinary feat to have it as customizable as it already is.

**Comment by UPS7868** [comment]
The dots look great! Thank you for being so quick to fix this! Keep up the awesome work! :)
