### ISSUE TITLE
QR code size inconsistency

### ISSUE THREAD

**Issue by felipedrumond** [kozakdenys/qr-code-styling#255]
I created two qr codes with very similar data (url) with the same configuration.

```const qrCode = new QRCodeStyling({
      width: 95,
      height: 95,
      margin: 3,
      data: url,
      image: 'favicon.ico',
      dotsOptions: {
        color: '#000',
        type: 'rounded',
      },
      backgroundOptions: {
        color: '#D9D9D9',
      },
      imageOptions: {
        crossOrigin: 'anonymous',
        margin: 5,
        imageSize: 0.6,
      },
    });

    qrCode.append(this.canvas.nativeElement);
```

When the url is 'http://localhost:4200/guide-cover/47/leave-hubby-on-the-couch-solo-in-barcelona', I get this qr code: 
![image](https://github.com/user-attachments/assets/be45ecc2-add0-4590-825a-16c559089dd4)

When the url is 'http://localhost:4200/guide/1/a', the qr has the correct size set in the configuration: 
![image](https://github.com/user-attachments/assets/13e5e254-f196-43af-9649-706394351922)

Is there a way to tell the qr code to always be the specified size?

**Comment by kozakdenys** [comment]
@felipedrumond hi, try to use 'dotsOptions.roundSize = false'

**Comment by felipedrumond** [comment]
That worked, thank you!
