### ISSUE TITLE
Add the option for color gradient 

### ISSUE THREAD

**Issue by FloMueh** [kozakdenys/qr-code-styling#27]
Hello out there, 

first thanks for this great library! 
I need to add an color gradient to the qr code.
Actually its not possible. I think the following snipped should do it (correct me i am wrong):

QRCanvas.ts Line 61:
```
var gradient = ctx.createLinearGradient(20,0, 220,0);
gradient.addColorStop(0, 'green');
gradient.addColorStop(.5, 'cyan');
gradient.addColorStop(1, 'green');
// Set the fill style and draw a rectangle
ctx.fillStyle = gradient;
ctx.fillRect(20, 20, 200, 100);
```

Of course we need some parameters for this, but it would be very great!

Thanks in advice and greetings

**Comment by kozakdenys** [comment]
Hi @FloMueh 
I added a gradient to `dotsOptions`, `backgroundOptions`, `cornersSquareOptions` and `cornersDotOptions` in v1.3.0.
For example, you can use it this way:
```
  const qrCode = new QRCodeStyling({
    data: "test",
    dotsOptions: {
      type: "rounded",
      gradient: {
        type: "linear",
        rotation: Math.PI * 0.2,
        colorStops: [{
          offset: 0,
          color: 'blue'
        }, {
          offset: 1,
          color: 'red'
        }]
      }
    }
```
Also, I updated http://qr-code-styling.com, you can play with gradient here as well :)

**Comment by FloMueh** [comment]
Hi @kozakdenys 
Great, thank you! love it!
