### ISSUE TITLE
feat: add extra rounded dots type

### ISSUE THREAD

**Issue by tafelnl** [kozakdenys/qr-code-styling#28]
It would be really awesome to support a design like this:
![image](https://user-images.githubusercontent.com/35837839/101512714-9b0ccc80-397b-11eb-88a7-59cf12e34d64.png)

It looks a bit like the 'rounded' option, but then even more rounded.

**Comment by kozakdenys** [comment]
Hi @tafelnl
Thanks for your idea.
I added it in version 1.3.0 so you can use it now this way:
```
  const qrCode = new QRCodeStyling({
    data: "test",
    dotsOptions: {
      type: "extra-rounded"
    },
    cornersSquareOptions: {
      type: "extra-rounded"
    }
  });
```
