### ISSUE TITLE
crop marks

### ISSUE THREAD

**Issue by scimsoft** [kozakdenys/qr-code-styling#37]
Hi Denys,
Thanks for this great library.
I am working on css crop marks for cutting the generated qr codes.
Maybe interesting include these in the qr generation process??

Thanks

**Comment by kozakdenys** [comment]
Hi @scimsoft 
Thank you for your idea.
At this stage of the project, I don't see the need for this feature. The library intended to be used as dynamically generated qr code on websites to scan it from mobile (it is the most common case).
I will leave this issue open to see other user's feedback, maybe someone else will request this feature.

**Comment by scimsoft** [comment]
Thank you Denys,

I use your library to generate bulk qr-codes, and then print them on sticker paper and cut them.

But I will do the crop marks outside the library.

Great library thanks again
