### ISSUE TITLE
Question: Why does the appended QR code appears different than the generated SVG?

### ISSUE THREAD

**Issue by nathakits** [kozakdenys/qr-code-styling#41]
Hi! I was wondering why is the appended QR code different than the generated SVG?
Excluding the image, the squares on the QR code don't match.

The appended QR code on the canvas
![image](https://user-images.githubusercontent.com/17331040/110510159-80422380-8135-11eb-9de1-201d9595239e.png)

The generated SVG using `qrcode._qr.createSVGTag()`.
![image](https://user-images.githubusercontent.com/17331040/110511078-7240d280-8136-11eb-9357-a0190ff1dcdc.png)

**Comment by J3ffJessie** [comment]
Did you have any rotation set within your options on the squares of the QR? It appears that it's the same QR code just rotated. Not sure if that helps diagnose any issues or not.

**Comment by kozakdenys** [comment]
@nathakits, please don't use private methods of this library (starts with _). It might change in every path and minor version. Use only methods from documentation.
