### ISSUE TITLE
Usage with Angular

### ISSUE THREAD

**Issue by ServiceSector** [kozakdenys/qr-code-styling#51]
Heya, I'm fiddling with this library in Angular. It doesn't seem to be binding to `<div id="canvas"></div>` 
Have you ever used this with Angular/is there any documentation for usage with NG?

**Comment by kozakdenys** [comment]
@ServiceSector please check this codesendbox https://codesandbox.io/s/agitated-panini-tpgb2?file=/src/app/app.component.ts
