### ISSUE TITLE
Downloaded QR code as SVG with image results in a broken image

### ISSUE THREAD

**Issue by erlingm69** [kozakdenys/qr-code-styling#55]
The SVG image tag representing the middle image is currently just using href but probably should be encoding the SVG content and embedding it using encodeURI with "data:image/svg+xml;utf8," and the image as SVG, like you shared in a previous discussion with me?

**Comment by mpmrepository** [comment]
I have this problem too, when I open the file in Adobe illustrator the image doesnt load

**Comment by kozakdenys** [comment]
Hi @erlingm69 it was released in version [v1.8.4](https://github.com/kozakdenys/qr-code-styling/releases/tag/v1.8.4)
