### ISSUE TITLE
No viewBox for SVG 

### ISSUE THREAD

**Issue by mpmrepository** [kozakdenys/qr-code-styling#60]
Hi, love the tool. I'm having a small problem with resizing the QR. In order for the PNG to export at the resolution required, I'm changing the width and height options to 1200, but this makes the SVG preview very large in the page, and I need it to stay small while being previewed.

This would be easy to do with CSS, but to resize an SVG you need a viewBox attribute specified and currently there isnt one, can you advise?

**Comment by kozakdenys** [comment]
Hi @mpmrepository, you can change the size of the canvas container via CSS.
For the [README](https://github.com/kozakdenys/qr-code-styling/blob/master/README.md) example it will be:
`...
<body>
<div id="canvas" style=" width: 100px; height: 100px;"></div>
<script type="text/javascript">
    const qrCode = new QRCodeStyling({
        width: 300,
        height: 300,
        ...
    });
    ...
</script>
</body>
...
`

**Comment by mpmrepository** [comment]
Thanks :) We actually need the SCG version rather than canvas for our purposes, but I've used 
`qrCode.firstChild.setAttribute('viewBox', '0 0 300 3000')` 
to achieve what i needed

**Comment by graemeblackwood** [comment]
@kozakdenys FWIW viewBox is critical if you want to generate inline SVGs that can resize dynamically. Without viewBox, the SVG just crops. This should be added by default.

**Comment by kozakdenys** [comment]
Hi @graemeblackwood @mpmrepository
Sorry for missing
It was fixed in [v1.8.0](https://github.com/kozakdenys/qr-code-styling/releases/tag/v1.8.0)
