### ISSUE TITLE
Ни один QR код, созданных в этой библиотеке не расшифровывается онлайн сканерами!

### ISSUE THREAD

**Issue by DewiarQR** [kozakdenys/qr-code-styling#73]
Браузерные онлайн сканеры QR кодов используют библиотеку zxing.js для расшифровки. Почему-то ни один из создаваемых в Вашей библиотеке QR-код не расшифровывается... может быть Вы подскажете, в чем может быть причина. 
Ваши QR - коды расшифровываются многими приложениями, но онлай сканерами нет. 
Вот попробуйте расшифровать здесь: https://dewiar.com/scan

**Comment by DewiarQR** [comment]
Проблема в неверном развороте мелких квадратиков в центральной части QR-кода. 
![Screenshot_2](https://user-images.githubusercontent.com/64423698/130450799-5559de6e-a51e-453f-8999-085e576dc0b7.png)

**Comment by BenBeri** [comment]
Как мы можем это исправить?

**Comment by kozakdenys** [comment]
Please, english only
