### ISSUE TITLE
Сохранение QR-кода работает неверно в случае SVG формата, если CANVAS - скачивается хорошо.

### ISSUE THREAD

**Issue by DewiarQR** [kozakdenys/qr-code-styling#75]
Если при активации библиотеки установить формат генерации QR-кода в SVG, а затем сохранить его на компьютер - сохраняется только начальная версия QR-кода, при дальнейшей модификации QR и попытке сохранить скачивается та самая первая версия QR-кода, которая получилась при загрузке страницы и начальной активации библиотеки.
Эта проблема есть только при SVG, если же выбрать канвас, проблемы такой нет, все сохраняется хорошо и правильно.

**Comment by kozakdenys** [comment]
Please, english only
