### ISSUE TITLE
Doesn't Work With Node

### ISSUE THREAD

**Issue by shellscape** [kozakdenys/qr-code-styling#87]
👋  hey there. you should put a big 'ol disclaimer at the top of your README that this doesn't work with Node, and only works in client-side browser apps. 

_(And this is actually kind of a shame, because I think if you separated the browser-specific code and shipped the compiled TS instead of the webpack bundle, this would work on node.)_

**Comment by mattgoulet** [comment]
I think this is a great idea. This library as a node library would fit my needs also.

**Comment by dlewis-irse** [comment]
I also would like to see this as a NodeJS Module - it's a nice QR code builder

**Comment by phgn0** [comment]
FYI this awesome work works out of the box in Node.js: https://github.com/Loskir/styled-qr-code

**Comment by phgn0** [comment]
FYI this fork works out of the box in Node.js: https://github.com/Loskir/styled-qr-code

**Comment by kozakdenys** [comment]
@shellscape @phgn0 @dlewis-irse @trymeouteh @mattgoulet  sorry for missing for so long 🥹

It was introduced in version [v1.6.0](https://github.com/kozakdenys/qr-code-styling/releases/tag/v1.6.0) and above 🎉
