### ISSUE TITLE
Remove padding

### ISSUE THREAD

**Issue by anarkrypto** [kozakdenys/qr-code-styling#88]
![image](https://user-images.githubusercontent.com/32111208/139539951-1f0f5b91-be94-4da6-895d-a03a280eb56c.png)

I need to remove or customize padding / empty space size. Excessive padding interferes with the interface.

**Comment by Damian710** [comment]
I'm facing the same issue. I can set a negative value to margin, but its getting ignored unless it is '-3' at least. But '-3' is a little bit too much, so that the qr code is cut off a little bit.

**Comment by marat-ad** [comment]
@anarkrypto see https://github.com/kozakdenys/qr-code-styling/issues/97#issuecomment-985902368 for details why this is happening.

**Comment by kozakdenys** [comment]
Duplicate of https://github.com/kozakdenys/qr-code-styling/issues/104.
You can use dotOptions.roundSize = false now.
More details in https://github.com/kozakdenys/qr-code-styling/issues/104#issuecomment-1771854501 and https://github.com/kozakdenys/qr-code-styling/issues/104#issuecomment-2425170881
