### ISSUE TITLE
Node.js support

### ISSUE THREAD

**Issue by tvajjhala** [kozakdenys/qr-code-styling#9]
Hey,
I'm building a mobile application using flutter, I'm planning on using google cloud functions to build the QR code and relay it to the app as a png/svg. Is there any way I can use this with node.js?

**Comment by kozakdenys** [comment]
Hi @tvajjhala
Thank you for your question!
Currently, this lib doesn't support node environment, it requires DOM functions. But I am planning to add support of such feature in the future releases.

**Comment by gabrielvega** [comment]
Hi! I'm interested in that support. Any news on this regard? May I help you with this development?

**Comment by kozakdenys** [comment]
Hi @gabrielvega
Thanks for reaching out, I will take a closer look at this issue and let you know, how you can help me with this.

**Comment by gabrielvega** [comment]
Hi @kozakdenys, I made a workaround with puppeteer, not the best solution but it's working so far. 

I'm thinking to spend hours of development work under your direction, you create the design and I can implement it. I don't have too much knowledge in this kind of developments so if you can give me some directions I will be happy and thrilled to do it!

The cool factor of your work is that you actually modify the QR depending on the logo you place in the middle, others solutions just place one image over the other and the QR code can be useless on different scenarios.

Let me know if this works for you.
Best regards`

**Comment by mr-piratman** [comment]
any news reguarding nodeJs support?

**Comment by nishagr** [comment]
> Hi @kozakdenys, I made a workaround with puppeteer, not the best solution but it's working so far.
> 
> I'm thinking to spend hours of development work under your direction, you create the design and I can implement it. I don't have too much knowledge in this kind of developments so if you can give me some directions I will be happy and thrilled to do it!
> 
> The cool factor of your work is that you actually modify the QR depending on the logo you place in the middle, others solutions just place one image over the other and the QR code can be useless on different scenarios.
> 
> Let me know if this works for you.
> Best regards`

Can you please explain the process for doing so?
I also wanted to run this package in a node environment. Thank you in advance.

**Comment by kozakdenys** [comment]
@mr-piratman @nishagr, sorry, but no luck with node support yet. It turned out a more difficult task than I expected so I postponed it.

**Comment by mr-piratman** [comment]
I guess I'll must using it on the client side. 
Thank you in any way. Amazing library. 🍻

**Comment by LAMike310** [comment]
Thanks for this library, I'm also looking for a NodeJS solution but Puppeteer is a good idea for a workaround!

Best looking QR codes I've found so far

**Comment by nishagr** [comment]
@LAMike310 Can you please let me know how to use the Puppeteer workaround? Thank you.

**Comment by mrfrase3** [comment]
I needed this so I implemented it in my PR.

Basically supports BYO node-canvas, as it's not very portable and best to leave it to the end-developer to set up and to pass through. It also means it won't be included in any bundle for browser implementations.

Doing it this way means you can get it working in something [like a lambda endpoint.](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:990551184979:applications~lambda-layer-canvas-nodejs)

**Comment by LAMike310** [comment]
> @LAMike310 Can you please let me know how to use the Puppeteer workaround? Thank you.

I ended up doing this:

Starting a server on Digital Ocean 
Create a "Create React App" with a react-router template on the server
Configure the React app to accept parameters (www.exapmle/[QR_DATA]))
Run the React App locally on your server, port 3000
Use puppeteer to take a screenshot on a simple Express app running on port 3001

```
(async () => {
        const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});
        const page = await browser.newPage();
        page.setViewport({width: 600, height: 600 });

        await page.goto(`http://localhost:3000/reward/${id}`);

        await page.screenshot({
            path: `screenshot/qrCode-${imageID}.png`,
        });
        await browser.close();
})();
```

**Comment by randomprogramming** [comment]
@mrfrase3's PR has been open with no update for 2 months now, any updates on this? Would really love this feature

**Comment by CiriousJoker** [comment]
I got it working by using this forked package: https://www.npmjs.com/package/qr-code-styling-node

I needed some additional code though to make it work:

```ts
import QRCodeStyling from "qr-code-styling-node";

global.window = new JSDOM().window as any;
global.self = global.window;
global.document = global.window.document;
// Only necessary when using "canvas" as image type
// global.Image = (Canvas as any);
global.XMLSerializer = global.window.XMLSerializer;

const qrCode = new QRCodeStyling({
  width: 256,
  height: 256,
  jsdom: JSDOM as any,
  type: "svg", // canvas doesn't seem to make a difference
  data: "some data",

  // I used the datauri package to convert my logo
  image: "some data uri",
  // ...
});

// .png export doesn't work, no matter what I do.
const svgBuffer = await qrCode.getRawData("svg") as Buffer;

// As a workaround, I converted the result using the svgexport package
fs.createWriteStream("temp.svg").write(svgBuffer);

svgexport.render([
  {
    input: [pathFileTemp],
    output: [pathFile]
  }
]);
```

**Comment by franzenitlab** [comment]
@CiriousJoker I've tried to follow your steps creating a Cloud Function in Typescript but I only get an 
`ReferenceError: self is no defined`, on your package `r-code-styling-node/lib/qr-code-styling.js:1:208)`. 

Any idea around this? Has to be something related to `global.self = global.window` or node environment? I am stuck on this.

Thank you!

**Comment by CiriousJoker** [comment]
@franzenitlab I fixed the code, my bad.

**Comment by dupasj** [comment]
I successfully transpile the code to run on a server with the [canvas](https://www.npmjs.com/package/canvas)'s package !
I already test it, I just cannot build svg version (didn't see how the project runs to export a svg image)

I would like to share my code but my code is really ugly ^^' (I remove all the test unit + configurations files)

**Comment by slavafomin** [comment]
The QR-codes generated by this library looks really cool, it's sad that there's no Node.js support, we would definitely like to use it in our server-side application.

**Comment by sunny-2504** [comment]
> @mr-piratman @nishagr, sorry, but no luck with node support yet. It turned out a more difficult task than I expected so I postponed it.

Is it released yet?

**Comment by rafagomes** [comment]
For future reference guys, I used this package and works like a charm.
https://socket.dev/npm/package/@loskir/styled-qr-code-node

**Comment by themaniacalfry** [comment]
@kozakdenys or anyone else. Have you been able to build this without the need for rust or puppeteer? I'm looking to deploy this to a node server that has been limited and can't execute external code or other languages. So the index.node c++ rust process causes it it to fail with error: `/var/task/node_modules/skia-canvas/lib/v6/index.node: invalid ELF header`.

I also can't launch a headless chrome window. 

Any help you all can provide would be greatly appreciated.

**Comment by bigirishlion** [comment]
> I got it working by using this forked package: https://www.npmjs.com/package/qr-code-styling-node
> 
> I needed some additional code though to make it work:
> 
> ```ts
> // This part is required before importing qr-code-styling-node
> // https://github.com/kozakdenys/qr-code-styling/issues/9
> import 'node-self';
> global.window = new JSDOM().window as any;
> global.self = global.window;
> global.document = global.window.document;
> // Only necessary when using "canvas" as image type iirc
> // global.Image = (Canvas as any);
> global.XMLSerializer = global.window.XMLSerializer;
> import QRCodeStyling from "qr-code-styling-node";
> 
> const qrCode = new QRCodeStyling({
>   width: 256,
>   height: 256,
>   jsdom: JSDOM as any,
>   type: "svg", // canvas doesn't seem to make a difference
>   data: "some data",
> 
>   // I used the datauri package to convert my logo
>   image: "some data uri",
>   // ...
> });
> 
> // .png export doesn't work, no matter what I do.
> const svgBuffer = await qrCode.getRawData("svg") as Buffer;
> 
> // As a workaround, I converted the result using the svgexport package
> fs.createWriteStream("temp.svg").write(svgBuffer);
> 
> svgexport.render([
>   {
>     input: [pathFileTemp],
>     output: [pathFile]
>   }
> ]);
> ```

This works great until I try and add an image. It appears to be hitting `const svgBuffer = await qrCode.getRawData("svg") as Buffer;` then breaking out of the process and not generating the SVG QR Code. Any ideas why?

```javascript
{
    image: "https://upload.wikimedia.org/wikipedia/commons/5/51/Facebook_f_logo_%282019%29.svg",
    imageOptions: {
        margin: 8,
        hideBackgroundDots: false
    },
    data: "some_data",
}
```

**Comment by phgn0** [comment]
> For future reference guys, I used this package and works like a charm. https://socket.dev/npm/package/@loskir/styled-qr-code-node

+1 for this awesome fork! It works out of the box in Node.js without any other patching.

You can leave some stars for it here: https://github.com/Loskir/styled-qr-code

**Comment by kozakdenys** [comment]
Hi folks, Sorry for missing here for so long time. I finally came back to this project. Thanks @mrfrase3 for his PR 💪 I just merged it and made the NPM release so that you can try it out 🎉
PS: I promise to continue supporting this library, I left my job to focus on projects I like to do 😉

**Comment by hoangdang02** [comment]
> [@kozakdenys](https://github.com/kozakdenys) or anyone else. Have you been able to build this without the need for rust or puppeteer? I'm looking to deploy this to a node server that has been limited and can't execute external code or other languages. So the index.node c++ rust process causes it it to fail with error: `/var/task/node_modules/skia-canvas/lib/v6/index.node: invalid ELF header`.
> 
> I also can't launch a headless chrome window.
> 
> Any help you all can provide would be greatly appreciated.

can you fixed it ?? i have issue like you after using lastest version styled-qr-code-node
