### ISSUE TITLE
Options Helpers are not working

### ISSUE THREAD

**Issue by krishnadeveloper** [kozakdenys/qr-code-styling#91]
Hi 
NPM Package : https://www.npmjs.com/package/qr-code-styling
Website : https://qr-code-styling.com/

Using with : ReactJs (v : ^17.0.2)

Example : 
     BackhroungOption : There is an option for COLOR TYPE : 1) Single Color , 2) Gradient Color. If I select option 2 that gradient color and update their property. Its working find till here . When I Re-Select option 1 that single color then still gradient color shows in background. 
     
So I found that cornersDotOptionsHelper, backgroundOptionsHelper and more option helpers are missing.

**Comment by krishnadeveloper** [comment]
@kozakdenys , did you get a chance to look into it?

**Comment by kozakdenys** [comment]
Can't reproduce it, if it is still relevant, please reopen
