### ISSUE TITLE
Exported svg clip paths cannot be imported into other tools

### ISSUE THREAD

**Issue by dasheck0** [kozakdenys/qr-code-styling#92]
Hi,

I am exporting a QR Code with some basic settings (see below). The QR Code is readable by browser and file previewer. However, once I import it into Figma, I get the following (see attached screenshot). As far as I understood this is due to clip paths, that are currently not supported by Figma. Is it possible to export svg without clip paths, such that every tool is able to read the file correctly? If not is there a workaround you can propose (i.e. tools for converting clip-paths to whatever)? Thanks!

[Generated QR Code](https://github.com/kozakdenys/qr-code-styling/files/7514242/qr.4.svg.zip)
![Imported QR Code in Figma](https://user-images.githubusercontent.com/4851711/141150269-a33b4596-ec46-4c78-9fba-333ed39265c0.png)

**Comment by freddyyeddy** [comment]
This Could be Fixed By Removing the Clip Path Method Of Assigning Color to Doc and Using Class and Style Blocks to Handle this.

**Comment by freddyyeddy** [comment]
I was looking into it (code wise) and switching "http://www.w3.org/2000/svg", "clipPath" to "http://www.w3.org/2000/svg", "g". and add .setAttribute("class", 'QR'); then you add a style block inside the SVG element then set the chosen color to the QR element. But this will break any gradient flowing across the QR. the fix could be doing what is talked about in this thread https://stackoverflow.com/questions/53101754/how-do-i-fill-several-svg-path-by-one-gradient. Which might not work on the gradient too but at least where supported the gradient will display and where not it will fail over and still show a QR code.

**Comment by dasheck0** [comment]
Alright. Thank you haven't tried it yet. However, this seems rather complicated and is likely not viable. Also not sure what other tools might support that or not. Seems that the SVG standard isn't that standard after all (due to multiple versions) and various degree of implementation in some tools (i.e. Figma)

**Comment by freddyyeddy** [comment]
The (g) tag has been standard in svgs since their initial development.
While complicated it should be more widely supported than clip paths. The
clip path is only needed for gradients to be rendered across the qr. I'd
you don't have to have gradients then it's as simple as modifying the Js to
generate it all in a group and not clip path.

**Comment by SergejSi** [comment]
same issue

**Comment by iamdangavin** [comment]
See my comment here: #125 ([comment](https://github.com/kozakdenys/qr-code-styling/issues/125#issuecomment-1150502319))

**Comment by kozakdenys** [comment]
Hi folks,
It should be partially fixed in version [v1.8.0](https://github.com/kozakdenys/qr-code-styling/releases/tag/v1.8.0).
The image is still not displayed in Illustrator, but I can't fix it as Illustrator doesn't fully support SVG standard
