### ISSUE TITLE
How to generate using multiple data elements like form data

### ISSUE THREAD

**Issue by rammohangowd** [kozakdenys/qr-code-styling#95]
HI
I would like to generate QR code with form data like..I will be having one form which contains Name, DOB, Gender, Phone etc and when I submit it should generate QRCode and when I scan it should display all fields and values. Is there any option or anyway to add multiple data elements.? Please Suggest me. Thank you!

**Comment by chiptu** [comment]
data is just the text written on qrcode.

You should maybe make your multiple form and concatenate all in the data field

**Comment by NumanNaseerNomi** [comment]
You can store your form data as **JSON** form. You can easily manipulate JSON data anywhere.
**Like:**
{"fullName":"Numan Naseer Nomi", "nickName":"Nomi", "company":"NOMi"}
